"""empty message

Revision ID: 1aa9f427d444
Revises: 07fddb5fbc29
Create Date: 2020-06-29 17:44:02.580155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa9f427d444'
down_revision = '07fddb5fbc29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdfs_images',
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['Images.id'], ),
    sa.ForeignKeyConstraint(['pdf_id'], ['Pdfs.id'], ),
    sa.PrimaryKeyConstraint('pdf_id', 'image_id')
    )
    op.create_table('pages_images',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['Images.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['Pages.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_images')
    op.drop_table('pdfs_images')
    # ### end Alembic commands ###
