"""empty message

Revision ID: 1dfdf2cc37c5
Revises: 83497460de39
Create Date: 2020-05-30 16:25:17.158781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfdf2cc37c5'
down_revision = '83497460de39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('parent_page_id', sa.Integer(), nullable=False),
    sa.Column('child_page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_page_id'], ['Pages.id'], ),
    sa.ForeignKeyConstraint(['parent_page_id'], ['Pages.id'], ),
    sa.PrimaryKeyConstraint('parent_page_id', 'child_page_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parents')
    # ### end Alembic commands ###
