"""empty message

Revision ID: 339c069fd10c
Revises: bf0c0665547c
Create Date: 2021-11-08 15:52:21.281003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339c069fd10c'
down_revision = 'bf0c0665547c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('css', sa.String(length=1000), nullable=True))
    op.add_column('Notes', sa.Column('x', sa.Integer(), nullable=True))
    op.add_column('Notes', sa.Column('y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notes', 'y')
    op.drop_column('Notes', 'x')
    op.drop_column('Notes', 'css')
    # ### end Alembic commands ###
