"""empty message

Revision ID: 568731ae5744
Revises: dece02561de4
Create Date: 2023-09-06 12:52:36.900945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568731ae5744'
down_revision = 'dece02561de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('age_group', sa.String(length=128), nullable=True))
    op.add_column('Users', sa.Column('gender', sa.String(length=128), nullable=True))
    op.add_column('Users', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('Users', sa.Column('location', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'location')
    op.drop_column('Users', 'interests')
    op.drop_column('Users', 'gender')
    op.drop_column('Users', 'age_group')
    # ### end Alembic commands ###
