"""empty message

Revision ID: 5fbc2aa1ae2f
Revises: 5562a8bbfc95
Create Date: 2020-10-01 16:22:45.454712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbc2aa1ae2f'
down_revision = '5562a8bbfc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('verification_token', sa.String(length=128), nullable=True))
    op.add_column('Users', sa.Column('verification_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'verification_token_expiry')
    op.drop_column('Users', 'verification_token')
    # ### end Alembic commands ###
