"""empty message

Revision ID: 80b7bdba2724
Revises: 4ed93c0246c0
Create Date: 2023-08-11 22:14:34.830778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b7bdba2724'
down_revision = '4ed93c0246c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_links',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['Pages.global_id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['Pages.global_id'], )
    )
    op.add_column('Pages', sa.Column('official_parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Pages', 'Pages', ['official_parent_id'], ['global_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Pages', type_='foreignkey')
    op.drop_column('Pages', 'official_parent_id')
    op.drop_table('page_links')
    # ### end Alembic commands ###
