"""empty message

Revision ID: 83497460de39
Revises: 14aee83475a8
Create Date: 2020-05-20 17:40:07.856344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83497460de39'
down_revision = '14aee83475a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['Files.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['Pages.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('Files')
    # ### end Alembic commands ###
