"""empty message

Revision ID: bf0c0665547c
Revises: 6b7d20c7ba81
Create Date: 2021-10-30 12:54:24.426541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0c0665547c'
down_revision = '6b7d20c7ba81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notes', sa.Column('page_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Notes', 'Pages', ['page_id'], ['id'])
    op.add_column('ToDos', sa.Column('page_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_ibfk_1', 'ToDos', type_='foreignkey')
    op.create_foreign_key(None, 'ToDos', 'Pages', ['page_id'], ['id'])
    op.create_foreign_key(None, 'ToDos', 'ToDos', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ToDos', type_='foreignkey')
    op.drop_constraint(None, 'ToDos', type_='foreignkey')
    op.create_foreign_key('todos_ibfk_1', 'ToDos', 'Users', ['user_id'], ['id'])
    op.drop_column('ToDos', 'page_id')
    op.drop_constraint(None, 'Notes', type_='foreignkey')
    op.drop_column('Notes', 'page_id')
    # ### end Alembic commands ###
