"""empty message

Revision ID: 1da2a14613eb
Revises: a97602d49565
Create Date: 2020-07-24 13:52:16.788198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1da2a14613eb'
down_revision = 'a97602d49565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('visitor_page_id', sa.Integer(), nullable=False),
    sa.Column('visited_page_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visited_page_id'], ['Pages.id'], ),
    sa.ForeignKeyConstraint(['visitor_page_id'], ['Pages.id'], ),
    sa.PrimaryKeyConstraint('visitor_page_id', 'visited_page_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    # ### end Alembic commands ###
