"""empty message

Revision ID: 5562a8bbfc95
Revises: 1da2a14613eb
Create Date: 2020-09-30 16:05:38.523585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5562a8bbfc95'
down_revision = '1da2a14613eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('Users', sa.Column('password', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'password')
    op.drop_column('Users', 'is_active')
    # ### end Alembic commands ###
