"""empty message

Revision ID: a97602d49565
Revises: f6b7cf0070b8
Create Date: 2020-06-30 15:19:15.984750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a97602d49565'
down_revision = 'f6b7cf0070b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Pages', sa.Column('type', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Pages', 'type')
    # ### end Alembic commands ###
