"""empty message

Revision ID: f6b7cf0070b8
Revises: 1aa9f427d444
Create Date: 2020-06-29 17:46:14.465210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b7cf0070b8'
down_revision = '1aa9f427d444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages_pdfs',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('pdf_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['Pages.id'], ),
    sa.ForeignKeyConstraint(['pdf_id'], ['Pdfs.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'pdf_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_pdfs')
    # ### end Alembic commands ###
